homeassistant:
  name: Dev HA
  unit_system: metric
  time_zone: Europe/Kyiv

solar_inverter:
  device: fake
  scan_interval: 5
  queries: [QPIGS, QPIRI, QPIWS]

logger:
  default: info
  logs:
    custom_components.solar_inverter: debug