homeassistant:
  name: Dev HA
  unit_system: metric
  time_zone: Europe/Kyiv

solar_inverter:
  name: Master Power
  # device: fake
  device: /tmp/inverter
  scan_interval: 5
  queries: [QPIGS, QPIRI, QPIWS, QMOD]

logger:
  default: info
  logs:
    custom_components.solar_inverter: debug